export const words = [
  "Vue",
  "React",
  "Angular",
  "Responsive Design",
  "Front End Developer",
  "Full Stack Developer",
  "Back End Developer",
  "Node.js",
  "Express",
  "Sequelize",
  "Java",
  "Vue",
  "React",
  "Angular",
  "Responsive Design",
  "Front End Developer",
  "Full Stack Developer",
  "Back End Developer",
  "Node.js",
  "Express",
  "Sequelize",
  "Java",
  "Vue",
  "React",
  "Angular",
  "Responsive Design",
  "Front End Developer",
  "Full Stack Developer",
  "Back End Developer",
  "Node.js",
  "Express",
  "Sequelize",
  "Java",
  "Vue",
  "React",
  "Angular",
  "Responsive Design",
  "Front End Developer",
  "Full Stack Developer",
  "Back End Developer",
  "Node.js",
  "Express",
  "Sequelize",
  "Java",
  "Vue",
  "React",
  "Angular",
  "Responsive Design",
  "Front End Developer",
  "Full Stack Developer",
  "Back End Developer",
  "Node.js",
  "Express",
  "Sequelize",
  "Java",
];
